language: python
python:
  - 3.7

before_install:
- pip install poetry
install:
- poetry install
- poetry add codecov
- poetry run pip install .
script:
- snds -h
- poetry run flake8
- poetry run python -m pytest tests --cov=sndslib -v
after_success:
- codecov