# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "master", "dev" ]
  pull_request:
    branches: [ "master", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install
        poetry add codecov
        poetry run pip install .

    - name: Lint
      run: |
        poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test
      run: |
        poetry run python -m pytest tests --cov=sndslib -v

    - name: Entrypoint
      run: |
        snds -V
